name: Indigo Data Request
description: Request features, data, metrics for indigo data models
title: "Data Request: "
labels: [Needs Triage]
body:
- type: markdown
  attributes:
    value: |
      Thanks for taking the time to fill out the details of this request!
- type: input
  id: contact
  attributes:
    label: Contact Details
    description: How can we get in touch with you if we need more info?
    placeholder: ex. email@example.com OR @discord-user#8888
  validations:
    required: false
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for this feature.
    options:
    - label: I have searched the existing issues
      required: true
- type: textarea
  attributes:
    label: Is your feature request related to a business or technical problem / opportunity? Please describe.
    description: A clear and concise description of what the problem or opportunity is.
  validations:
    required: false
- type: textarea
  attributes:
    label: Describe the solution you'd like and alternatives you've considered
    description: A clear and concise description of what you want to happen, and any alternative solutions or features you've considered.
  validations:
    required: false
- type: textarea
  attributes:
    label: How will you use this data/feature?
    description: Technical and operational use for the feature. |
      Example -> We will query the metric for each of our active customers every 5 minutes using snowflake sdk and send a notification to their browser. This will increase customer time on our site and help upsell premium service X.
  validations:
    required: false
- type: textarea
  attributes:
    label: What is the business impact?
    description: |
      Describe the increase in data coverage or accuracy, the projected revenue impact, the impact on data engagement / usability, saved time, customer acquisition or retention, etc. Provide numbers when possible.
  validations:
    required: false
- type: textarea
  attributes:
    label: Relevant contracts or transactions.
    description: |
      Please provide etherscan/block explorer links and screenshots with descriptions to provide a complete picture for mapping the raw data to the desired feature.
  validations:
    required: false
- type: textarea
  attributes:
    label: What is the scope of this feature?
    description: |
      Is this for a specific edge case or is it a general / protocol level data feature that will encompass blockchain transactions beyond the specific contracts/transactions provided.
  validations:
    required: false
- type: textarea
  attributes:
    label: For non-general features, please provide additional edge cases to be included.
    description: |
      For edge cases / contract specific scope, please be thorough in investigating similar edge cases that can be included in the same scope of work. Describe your investigation here.
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional context.
    description: |
      Add any other context, references, or screenshots about the feature request here.
  
      Tip -> You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
